// docs/API.md from docs/syrinx-docs.json: the generated API reference in a form GitHub renders, the
// core module and then the framework's modules (SPEC.md, clauses 12-13).
//
//   node tools/api-md.mjs [docs/syrinx-docs.json] [docs/API.md]
//
// test/docs.test.js regenerates it and fails when the committed file is behind.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** The reference as Markdown. Pure, so the test can compare without writing. */
export function apiMarkdown(docs) {
  const out = [];
  out.push("# API reference", "");
  out.push(
    "Generated by `syrinx docs` from `prelude/syrinx.d.ts` and the framework's declarations -- do not edit.",
    `syrinx ${docs.version}: contract version ${docs.api} (a source declares \`meta.api\` ${docs.apiFloor}` +
      `${docs.apiFloor === docs.api ? "" : ` to ${docs.api}`}), streams in blocks of ${docs.blockFrames} frames.`,
    "",
  );
  /** A module's groups at heading `level`, its entries one below. */
  const entries = (groups, level) => {
    for (const group of groups) {
      if (!group.entries.length) continue;
      out.push(`${"#".repeat(level)} ${group.name}`, "");
      for (const e of group.entries) {
        out.push(`${"#".repeat(level + 1)} \`${e.name}\``, "", "```ts", e.signature, "```", "");
        if (e.doc) out.push(e.doc, "");
        if (e.values?.length) out.push(`One of: ${e.values.map((v) => `\`"${v}"\``).join(", ")}.`, "");
        for (const m of e.members ?? []) {
          out.push(`- \`${m.isStatic ? "static " : ""}${m.signature}\`${m.doc ? ` -- ${m.doc.replaceAll("\n", " ")}` : ""}`);
        }
        if (e.members?.length) out.push("");
      }
    }
  };
  const core = docs.modules.filter((m) => m.part === "core");
  const framework = docs.modules.filter((m) => m.part === "framework");
  out.push("## The core module", "", "What a conforming host must know about (SPEC.md, clause 12): `import ... from \"syrinx\"`.", "");
  for (const m of core) {
    if (m.summary) out.push(m.summary, "");
    entries(m.groups, 3);
  }
  out.push(
    "## The framework",
    "",
    "A library a project vendors (`syrinx framework <dir>`) and imports by relative path; never required of a host (SPEC.md, clause 13).",
    "",
  );
  for (const m of framework) {
    out.push(`### \`${m.module}\``, "");
    if (m.summary) out.push(m.summary, "");
    entries(m.groups, 4);
  }
  return out.join("\n").replace(/\n+$/, "\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [input = "docs/syrinx-docs.json", output = "docs/API.md"] = process.argv.slice(2);
  writeFileSync(output, apiMarkdown(JSON.parse(readFileSync(input, "utf8"))));
  console.log(`${output} from ${input}`);
}
