// docs/API.md from docs/syrinx-docs.json: the generated API reference in a form GitHub renders, split
// into the core module and the framework as the declarations mark them (SPEC.md, clauses 12-13).
//
//   node tools/api-md.mjs [docs/syrinx-docs.json] [docs/API.md]
//
// test/docs.test.js regenerates it and fails when the committed file is behind.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** The reference as Markdown. Pure, so the test can compare without writing. */
export function apiMarkdown(docs) {
  const out = [];
  out.push("# API reference", "");
  out.push(
    `Generated by \`syrinx docs\` from \`prelude/syrinx.d.ts\` -- do not edit. The \`"${docs.module}"\` module,`,
    `contract version ${docs.api} (a source may declare \`meta.api\` ${docs.apiFloor} to ${docs.api}), streams in blocks of`,
    `${docs.blockFrames} frames.`,
    "",
  );
  if (docs.summary) out.push(docs.summary, "");
  const section = (title, intro, keep) => {
    out.push(`## ${title}`, "", intro, "");
    for (const group of docs.groups) {
      const entries = group.entries.filter(keep);
      if (!entries.length) continue;
      out.push(`### ${group.name}`, "");
      for (const e of entries) {
        out.push(`#### \`${e.name}\``, "", "```ts", e.signature, "```", "");
        if (e.doc) out.push(e.doc, "");
        if (e.values?.length) out.push(`One of: ${e.values.map((v) => `\`"${v}"\``).join(", ")}.`, "");
        for (const m of e.members ?? []) {
          out.push(`- \`${m.isStatic ? "static " : ""}${m.signature}\`${m.doc ? ` -- ${m.doc.replaceAll("\n", " ")}` : ""}`);
        }
        if (e.members?.length) out.push("");
      }
    }
  };
  section("The core module", "What a conforming host must know about (SPEC.md, clause 12).", (e) => e.core);
  section("The framework", "Everything else the prelude ships today; not required of a host (SPEC.md, clause 13).", (e) => !e.core);
  return out.join("\n").replace(/\n+$/, "\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [input = "docs/syrinx-docs.json", output = "docs/API.md"] = process.argv.slice(2);
  writeFileSync(output, apiMarkdown(JSON.parse(readFileSync(input, "utf8"))));
  console.log(`${output} from ${input}`);
}
